import { OlysItem } from '../../../domain/entities/types'

export const mockTodayItems: OlysItem[] = [
  {
    id: '1',
    type: 'tarefa',
    title: 'Revisar estrutura operacional do release',
    state: 'active',
    essentialProtected: true,
    contextLabel: 'Release 1',
    scheduledLabel: 'Agora',
    durationMinutes: null,
    capacityDemand: 'medium',
  },
  {
    id: '2',
    type: 'projeto',
    title: 'Consolidar projections do Hoje',
    state: 'active',
    contextLabel: 'Fazer',
    scheduledLabel: 'Depois',
    durationMinutes: 90,
    capacityDemand: 'high',
  },
  {
    id: '3',
    type: 'tarefa',
    title: 'Validar dependencias criticas',
    state: 'blocked',
    dependency: {
      kind: 'blocker',
      reason: 'Aguardando decisao de escopo',
      impact: 'Pode atrasar a sequencia operacional da Timeline',
    },
    dueLabel: 'Ha 5 dias',
    scheduledLabel: 'Risco',
    contextLabel: 'Timeline',
    durationMinutes: null,
    capacityDemand: 'unknown',
  },
  {
    id: '4',
    type: 'inbox',
    title: 'Transformar notas soltas em decisao de produto',
    state: 'active',
    contextLabel: 'Captura',
    createdAtLabel: 'Hoje',
    inboxStatus: 'untriaged',
    durationMinutes: null,
    capacityDemand: 'unknown',
  },
]
